name: Build Docker image

on:
  - push
  - pull_request

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: build
      env:
        GIT_SHA: ${{ github.sha }}
        DOCKER_REPO: docker.pkg.github.com/${{ github.repository }}/motionzero-receiver
      run: |
        short_sha=$(printf $GIT_SHA | cut -c 1-7)
        docker build receiver --file receiver/Dockerfile --tag $DOCKER_REPO:$short_sha
        docker push $DOCKER_REPO

  # push:
  #   - ok
        
  # publish:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - 
